name: spotifuad
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.10.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Bloc
  flutter_bloc: ^6.1.3
  equatable: ^2.0.0

  # Firebase
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  firebase_storage: ^8.0.0
  google_sign_in: ^5.0.0

  provider: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  fonts:
    - family: Product Sans
      fonts:
        - asset: fonts/productsans.ttf
        - asset: fonts/productsans-italic.ttf
          style: italic